version: 2
updates:
  - package-ecosystem: docker
    directory: /src
    schedule:
      interval: daily
    ignore:
      - dependency-name: "mcr.microsoft.com/dotnet/sdk"
        versions: [">=9.0.0"]
  # spritely/build/container uses other spritely actions, some of which use the container produced by this repo as a devcontainer
  # Therefore enabling the code below would create a circular dependency, so build version updates are manual in this repo
  # - package-ecosystem: github-actions
  #  directory: /
  #  schedule:
  #    interval: daily
