name: Build and Publish Container

on: [push, workflow_dispatch]

# Permissions required for automatic semantic version tagging
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Build and publish container
        uses: spritely/build/container@improve-reuse
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          imageNames: spritelydev/dotnet8-devcontainer
          context: ./src/src
          dockerfile: ./src/src/Dockerfile
