name: Build and Publish Container

on: [push, workflow_dispatch]

# Permissions required for automatic semantic version tagging
permissions:
    contents: write

env:
  BUILD_VERSION_TAG: improve-reuse

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Build and publish container
        uses: spritely/build/steps/versioned-container-build@${{ env.BUILD_VERSION_TAG }}
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          imageNames: spritelydev/dotnet8-devcontainer
          context: ./src/src
          dockerfile: ./src/src/Dockerfile
