name: Build and Publish Container

on: [push, workflow_dispatch]

# Permissions required for automatic semantic version tagging
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Build and publish container
        # spritely/build/container uses other spritely actions, some of which use the container produced by this repo as a devcontainer
        # Therefore automatic dependency updates would create a circular dependency, so build version updates are manual in this repo
        uses: spritely/build/container@v0.19.0
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          imageNames: spritelydev/dotnet8-devcontainer
          context: ./src
          dockerfile: ./src/Dockerfile
